# Blueprint de Render para la aplicación PRzone
# Versión final que usa un contenedor Docker personalizado para Nginx.

services:
  # 1. Servicio del Backend (Node.js)
  - type: web
    name: backend
    env: docker
    repo: https://github.com/GuilleAlvareez/PRzone-Completo
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: BETTER_AUTH_URL
        fromService:
          type: web
          name: proxy
          property: url
      - key: CLIENT_URL
        fromService:
          type: web
          name: proxy
          property: url
      - key: DB_HOST
        value: "aws.connect.psdb.cloud"
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: "p0eykwvk68h8pi7u5bia"
      - key: DB_NAME
        value: "przone"
      - key: model
        value: "mistralai/devstral-small:free"
      # --- CLAVES SECRETAS (configurar en el Dashboard de Render) ---
      - key: BETTER_AUTH_SECRET
        sync: false
      - key: API_KEY
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false

  # 2. Servicio del Frontend (React servido por Nginx)
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/GuilleAlvareez/PRzone-Completo
    dockerfilePath: ./frontend/Dockerfile

  # 3. Servicio del Proxy Inverso (Nginx)
  # Este es el ÚNICO servicio público.
  - type: web
    name: proxy
    env: docker # <-- CAMBIO CLAVE: Usamos Docker en lugar de 'nginx'
    repo: https://github.com/GuilleAlvareez/PRzone-Completo
    # No necesitamos un Dockerfile para Nginx, podemos usar la imagen oficial
    # y montar nuestra configuración. Render lo maneja con estas propiedades:
    dockerCommand: nginx -c /etc/nginx/nginx.conf -g 'daemon off;'
    dockerContext: ./nginx # Le decimos dónde está el contexto (el archivo de config)
    # Render necesita saber qué puerto exponer, aunque ya lo definimos en nginx.conf
    envVars:
      - key: PORT
        value: 80