# Blueprint de Render para la aplicación PRzone
# Versión final que usa un Private Service para el proxy Nginx.

services:
  # 1. Servicio del Backend (Node.js) - Ahora es un servicio privado
  - type: pserv # pserv = Private Service
    name: backend
    env: docker
    repo: https://github.com/GuilleAlvareez/PRzone-Completo
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: BETTER_AUTH_URL
        fromService:
          type: web
          name: proxy
          property: url
      - key: CLIENT_URL
        fromService:
          type: web
          name: proxy
          property: url
      - key: DB_HOST
        value: "aws.connect.psdb.cloud"
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: "p0eykwvk68h8pi7u5bia"
      - key: DB_NAME
        value: "przone"
      - key: model
        value: "mistralai/devstral-small:free"
      # --- CLAVES SECRETAS (configurar en el Dashboard de Render) ---
      - key: BETTER_AUTH_SECRET
        sync: false
      - key: API_KEY
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false

  # 2. Servicio del Frontend (React servido por Nginx) - También es un servicio privado
  - type: pserv # pserv = Private Service
    name: frontend
    env: docker
    repo: https://github.com/GuilleAlvareez/PRzone-Completo
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile

  # 3. Servicio del Proxy Inverso (Nginx) - ¡AHORA ES EL ÚNICO SERVICIO PÚBLICO!
  - type: web # Este es el único 'web' service, el que se expone a internet.
    name: proxy
    env: nginx # Volvemos a usar el entorno optimizado de Nginx
    repo: https://github.com/GuilleAlvareez/PRzone-Completo
    # Usamos las reglas de reescritura nativas de Render, que son más sencillas
    rules:
      - type: rewrite
        source: /api/(.*)
        destination: /api/$1
      - type: proxy
        source: /api/(.*)
        destination: http://backend:3000/$1
      - type: rewrite
        source: /(.*)
        destination: /index.html
      - type: proxy
        source: /(.*)
        destination: http://frontend